version: "3"

services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py collecstatic --no-input &&
      gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=supersecretpassword
      - ENV=prod
    depends_on:
      - db
    expose:
      - 8000

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    volumes:
      - ./app/static:/app/static
      - ./app/media:/app/media
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - app

